### ISSUE TITLE
brew formula not found

### ISSUE THREAD

**Issue by devalnor** [reorx/httpstat#16]
Error: No available formula with the name "httpstat"

**Comment by reorx** [comment]
```
$ brew info httpstat
httpstat: stable 1.1.3
Curl statistics made simple
https://github.com/reorx/httpstat
/usr/local/Cellar/httpstat/1.1.3 (3 files, 9.2K)
  Built from source on 2016-09-11 at 16:27:08
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/httpstat.rb
```

Have you tried `brew update` first?

**Comment by lucasallan** [comment]
It works for me.

**Comment by hackerrdave** [comment]
Running `brew update` will fetch the latest Homebrew updates. `httpstat` will be available as a formula afterwards.

**Comment by reorx** [comment]
I'll treat this issue as solved, but anyone comes up with the same problem can still comment here to let me know.
