### ISSUE TITLE
Homebrew

### ISSUE THREAD

**Issue by Mazyod** [reorx/httpstat#2]
Will there be a release on Homebrew? `httpstat` is available, too.

**Comment by reorx** [comment]
Hmm, this is definitely a nice-to-have option, thanks for mentioning! I will try to write a formula and submit to homebrew-core for review.

**Comment by reorx** [comment]
I have submitted the formula to homebrew-core, let's wait for their review https://github.com/Homebrew/homebrew-core/pull/4610

**Comment by reorx** [comment]
```
$ brew update
Updated Homebrew from 2815485 to 592f584.
Updated 2 taps (caskroom/cask, homebrew/core).
==> New Formulae
httpstat ✔
```

Now available on homebrew!
