### ISSUE TITLE
Provide Average based on number of attempts over time

### ISSUE THREAD

**Issue by InAnimaTe** [reorx/httpstat#21]
This is a feature req. that I just thought of. I've been doing some testing of proxy servers and have used to httpstat to gain insight into how long each part of the connection process takes. To make httpstat even more adept to performance based testing like this, it would be exceptionally awesome if it had the option for making x number of requests over y timeframe and providing those results in a similar drawing to how it currently does i.e. TLS Handshake avg, Server Processing avg, etc..

Just a thought ;)

**Comment by reorx** [comment]
I've also come up with the similar idea when testing server latency, but when it goes to the situation where multiple requests should be made to calculate average number, what we are doing is not just visualize one or few requests, but a HTTP benchmarking work. Thus I think using professional benchmark tool like [apache ab](http://httpd.apache.org/docs/2.4/programs/ab.html) would be better, and easier. `ab` can give you the timing summary of each phase that you wanted, not that pretty as `httpstat` does, but I thinks it's more detailed and more serious as a statistic report.

```
Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       40   43   2.2     42      48
Processing:    40   45   4.1     44      55
Waiting:       40   44   4.2     43      55
Total:         80   87   4.9     86      97
```

`httpstat` should remain its simplicity - gain insight for one particular request, and let the  specialized job be done by specialized tools. Don't you think so?

**Comment by InAnimaTe** [comment]
I completely agree ;) Thanks for the detailed reply! I'll have to check out apache ab then; definitely looks like exactly what im looking for.
