### ISSUE TITLE
Snapcraft.yaml for httpstat

### ISSUE THREAD

**Issue by simos** [reorx/httpstat#30]
I am a user of httpstat and I used httpstat as an example to show how to package software as snaps (https://www.ubuntu.com/desktop/snappy). 

To make a snap for a software package, you need to create a snapcraft.yaml configuration file. 
Here is the one for httpstat: https://gist.github.com/simos/3214bbd2f7d4a4647918bdb2afb926cd

How to create the snap?
1. Install snapcraft 2.26 (default in Ubuntu 16.04 or newer)
2. Run "snapcraft" in the same directory that has the snapcraft.yaml from the gist.
3. The httpstat_1.1.3_amd64.snap will be produced. 

I wrote an article about all this at https://blog.simos.info/how-to-create-a-snap-for-a-python-app-with-networking-using-snapcraft-in-ubuntu-16-04/

I understand that someone would simply need to grab the .py file and run it. I am posting this issue to inform that I have used "httpstat" as an example for my tutorial.

**Comment by reorx** [comment]
Great article, thanks for sharing!
