### ISSUE TITLE
Lamentable screenshot

### ISSUE THREAD

**Issue by szepeviktor** [reorx/httpstat#37]
Hello! This is a nice project.

Please display an image of a high performance webserver to boost morale.

![kép](https://user-images.githubusercontent.com/952007/94178037-d4fd2500-fe9a-11ea-8657-6ffffc2f069e.png)

**Comment by reorx** [comment]
Thanks for your suggestion, but I think most of the situations where httpstat is involved are because of high latency, showing a case like that is easier for people to understand😀.

Specially, I want every number in the chart to be larger than 0, as a proof that every metric works.

**Comment by szepeviktor** [comment]
Okay.
Thank you for the explanation.
