### ISSUE TITLE
这是抄袭了https://github.com/davecheney/httpstat吗？

### ISSUE THREAD

**Issue by hongmaoxiao** [reorx/httpstat#42]
看这个https://github.com/davecheney/httpstat 库的时候，它的readme里有这样一句

> But seriously, https://github.com/reorx/httpstat is the new hotness, and this is a shameless rip off.

就好奇问问

**Comment by reorx** [comment]
感谢关注，`reorx/httpstat` 先出，受到欢迎后 Dave 重新用 go 做了实现也就是 `davecheney/httpstat` 。

这句话表达的意思是，`reorx/httpstat` 是最近的新热门项目，`davecheney/httpstat` 是「无耻」的「抄袭」。不过我们都知道，这是 Dave 的谦虚和幽默，`httpstat` 是以 MIT 协议发布的，大家友好交流互相启发，不存在真的抄袭一说，并且独立的 go 实现更有技术含量，我的项目不过是在 TUI 上做了点小创意罢了，本不值得被如此关注。

**Comment by hongmaoxiao** [comment]
> 感谢关注，`reorx/httpstat` 先出，受到欢迎后 Dave 重新用 go 做了实现也就是 `davecheney/httpstat` 。
> 
> 这句话表达的意思是，`reorx/httpstat` 是最近的新热门项目，`davecheney/httpstat` 是「无耻」的「抄袭」。不过我们都知道，这是 Dave 的谦虚和幽默，`httpstat` 是以 MIT 协议发布的，大家友好交流互相启发，不存在真的抄袭一说，并且独立的 go 实现更有技术含量，我的项目不过是在 TUI 上做了点小创意罢了，本不值得被如此关注。

不好意思，英文水平不够，理解错了，打搅了
