### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by hemangsk** [reorx/httpstat#9]
First off Great software !
and the screenshot looks pretty awesome too can you please tell how can I modify my terminal to get that black window bar and that awesome font! I am on macOS.

Thanks! 😄

**Comment by reorx** [comment]
The terminal I use for screenshot is HyperTerm https://hyperterm.org/

As to the color scheme and font, I will check my config to give more information tomorrow (I'm afk at home now :)

**Comment by hemangsk** [comment]
Hey Xiao Thanks a ton!! 😄 
surely I'll wait please let me know the color scheme and fonts whenever u wish 👍 👍 They look pretty amazing

**Comment by reorx** [comment]
- color scheme plugin: [hyperterm-base16-tomorrow-dark](https://github.com/d3viant0ne/hyperterm-base16-tomorrow-dark)
- font family: [Hack](https://github.com/chrissimpkins/Hack)

Hope this helps

**Comment by hemangsk** [comment]
Thanks again 😄 its awesome!
Happy Coding!
